inherit_from:
  - .rubocop_airbnb.yml


AllCops:
  Exclude:      
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/**/*'
    - 'Gemfile'
    - 'app/helpers/**/*' 
    - 'db/**/*'
    - 'config/initializers/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/spring.rb'
    - 'config/routes.rb'
    