inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:      
    - spec/**/*    
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/**/*'
    - 'Gemfile'
    - 'app/helpers/**/*' 
